library(reshape2)
a=read.table('FPKM.txt',sep = '\t',stringsAsFactors = F)
aa<-melt(a)
fpkm <- dcast(aa,formula = V1~V3)
write.table(fpkm, file = "FPKM.tab",col.names = TRUE,row.names = FALSE, sep = "\t")
b=read.table('TPM.txt',sep = '\t',stringsAsFactors = F)
bb<-melt(b)
tpm <- dcast(bb,formula = V1~V3)
write.table(tpm, file = "TPM.tab",col.names = TRUE,row.names = FALSE, sep = "\t")
