##################### 11 Syntenic analysisf with GENESPACE ################################
# Syntenic analysis
library(GENESPACE)
runwd <- file.path("~/Project/Armyworms/04_Evolution/Syntenicanalysis")
list.files(runwd, recursive = T, full.names = F)
gpar <- init_genespace(
  genomeIDs = c("Mlor","Msep","Sfru","Aips","Harm","Sexi","Tni"),
  speciesIDs = c("Mlor","Msep","Sfru","Aips","Harm","Sexi","Tni"),
  versionIDs = c("Mlor","Msep","Sfru","Aips","Harm","Sexi","Tni"),
  outgroup = NULL,
  ploidy = rep(1,7),
  diamondMode = "fast",
  orthofinderMethod = "fast",
  wd = runwd,
  orthofinderInBlk = FALSE, 
  overwrite = F, 
  verbose = T,
  nCores = 4,
  minPepLen = 50,
  gffString = "gff",
  pepString = "pep",
  path2orthofinder = "orthofinder",
  path2diamond = "diamond",
  path2mcscanx = "~/MCScanX",
  rawGenomeDir = file.path(runwd, "rawGenomes"))

parse_annotations(
	gsParam = gpar,
	gffEntryType = "gene",
	gffIdColumn = "ID",
	gffStripText = "ID=",
	headerEntryIndex = 1,
	headerSep = " ",
	headerStripText = "ID=")
gpar <- run_orthofinder(gsParam = gpar)
gpar <- set_syntenyParams(gsParam = gpar,blkSize=5)
gpar <- synteny(gsParam = gpar)

ripSouceDat <- plot_riparianHits(
     gpar, 
     refGenome = "Aips",
     genomeIDs = c("Tni","Sfru","Sexi","Harm", "Aips","Mlor", "Msep"),
     blackBg = FALSE, invertTheseChrs = data.frame(genome = c("Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Msep","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Mlor","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Harm","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sexi","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Sfru","Tni","Tni","Tni","Tni","Tni","Tni","Tni","Tni","Tni","Tni"), chr = c(1,3,5,6,8,9,11,12,14,16,19,20,21,22,23,24,29,31,2,3,4,10,12,15,21,22,24,26,31,1,5,4,10,14,2,6,17,9,8,18,15,19,25,21,26,29,27,1,18,29,6,12,21,14,25,16,7,20,27,30,2,11,24,2,3,9,6,10,8,14,15,20,21,24,27,30,28,31,29,1,18,11,6,12,21,14,16,7,20)), 
     returnSourceData = T, 
     verbose = F)
